sudo: required

services:
- docker

language: generic

env:
  global:
    secure: cYSFGaMbyDFI0nAb2ZAsItmD/POH/gcfCGEKJ6/d6LjUWXPw680ZEEvHeqLD+852kj4eTLgtE/bOrPh7Zmp3k4LzwiBU437Qb5otdQwhkbIS3GgIwRSGz8gkSSvI5Cx+N1IncBcuuzahzT80afh3sMtTewmZDz7OycrZEqoCZSnU+L3lFcSmZFMoAhybLyxmtAAam0CE3Jt/6/swiSCLTSSCfLiWIfmxFIDOn85uaJZqObmfKL7CQcmlqQTiYoW+OHnUUBA5tYBbpXk0jc+jofNsMddGyrGBrHRs3bukZOBWq8Ck7XdrEjQ4S2l7AjFXI2R9Ve4J/NLHZ3mgydKWTQ6Xr293FK+9Nq8hIsNsEMwHo48uz8JtKQK4VyKoejpPS1rfhF3SAsDo5xLJ1JgNK0k65HXkR12X1nOptweZy2727nz404QOnXSbW1sUz44e8f9FTYuOFy1Mq2qSek6tlYlPsjKRWY+92bo3JTOpAFve1dpgG+OIqvhoMrWP6LMcM9SteApa36RSv1kxI1cLCLwkyIXK9Tg/HP4vR/NI3TNFkZLB6G9tzXYUyvuK1dBb6WuZiOJxennk31wtThdZtK0rfwNwDIxX5dblIzG4DDohI1m+aCzdx4pDAxf3z+b4zPLEyaWCSLWExMCwvMG2E0F/QqJt2nkTG5AYYgh1DV8=

script:
- make push
